version: "3.9"

services:
  webserver:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8080:80"    # akses via http://localhost:8080
    volumes:
      - ./html:/usr/share/nginx/html   # folder lokal html -> folder nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # opsional, jika mau custom config
    networks:
      - appnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"   # REST API Elasticsearch
      - "9300:9300"   # internal cluster comm
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - appnet

networks:
  appnet:

volumes:
  es_data:
