version: "3.9"

services:
  webserver:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    networks:
      - elknet
    restart: always
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elknet
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1

  logstash:
    image: logstash:8.15.0
    container_name: logstash
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5044:5044"
      - "5000:5000"
    depends_on:
      - elasticsearch
    networks:
      - elknet
    restart: always

  kibana:
    image: kibana:8.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elknet
    restart: always

  filebeat:
    image: elastic/filebeat:8.15.0
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/var/log/nginx:ro
    networks:
      - elknet
    depends_on:
      - logstash
    restart: always
    
  elastic-agent:
    image: elastic/elastic-agent:8.15.0
    container_name: elastic_agent
    user: root
    volumes:
      - ./elastic-agent.yml:/usr/share/elastic-agent/elastic-agent.yml:ro
      - ./logs:/var/log/nginx:ro   # ambil log dari container nginx
    networks:
      - elknet
    depends_on:
      - elasticsearch
    restart: always

networks:
  elknet:

volumes:
  es_data:
